# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16608bf445effc6eb3c7bf7994f8c822caf971dfaa22f59b38899a0ff7dd036572db2633912599a425f0d150108a2edb78cc54cd95f924c3165e868aa7b3e89a

test:
  secret_key_base: 803367dfa33934d6d62b8c643a6e4cdb9eed05af5082c9b4ce676172bfdd7ab2f85958ed836a37ff10bae8687fde6d8d364413fb3703f73e14327dfa92d5b747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
